# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
